### ISSUE TITLE
Randomise drinks that appear on landing page carousel

### ISSUE THREAD

**Issue by iteles** [club-soda/club-soda-guide#121]
Splitting this portion of https://github.com/club-soda/club-soda-guide/issues/8 out as agreed with CS team it was a lower priority for now.

As a Club Soda administrator
I would like the list of featured drinks on the homepage to be randomised,
So that as our list grows and we have a large number of member brands and therefore a number of higher weighted drinks (#74) that exceeds the carousel limit, all drinks can get some 'air time' in the carousel.

## Acceptance Criteria
+ [x] Drinks displayed are randomised (each user should see a different set of drinks) - this may require us to fix the number of drinks in each weighting category displayed in the carousel, TBC

**Comment by Cleop** [comment]
So am I right in understanding that drinks with the highest weighting always take priority but that within the weighting's the drinks will appear in a randomised order? @iteles

**Comment by iteles** [comment]
@cleop That's exactly it :+1:

**Comment by jussi-club-soda** [comment]
I've been reloading the page a few times, and the same drinks keep coming up a lot - how "random" is the shuffle @Cleop ?

**Comment by Cleop** [comment]
The shuffle is based on the CS score. So if you had:

Drink 1, CS Score - 5
Drink 2, CS Score - 4
Drink 3, CS Score - 3
Drink 4, CS Score - 2
Drink 5, CS Score - 1
Drink 6, CS Score - 1
Drink 7, CS Score - 1
Drink 8, CS Score - 0

Only drinks 5,6,7 and 7 will shuffle because drink 1 will always come first due to its score. So it shuffles drinks within a score band. So if you want a greater deal of shuffling you need to 'favourite' more drinks to appear in the carousel so they can be shuffled for each score.

**Comment by Cleop** [comment]
@jussi-club-soda 

The shuffle mixes up the drinks within the same weighting band. So that the highest weighted drinks always appear first. So if you have 5 drinks at the highest weighting then they will shuffle between themselves before displaying all drinks of a lower weighting. But if you have 1 drink per weighting then those drinks won't shuffle as there's no other drinks of the same weighting to shuffle them with.

Does that make sense?

**Comment by jussi-club-soda** [comment]
Thanks @Cleop that does make sense - I think with this one we need to do some experimenting to get a feel on how best to use it for our purposes!
