### ISSUE TITLE
Stop bot attacks on venue listings & nominate a venue form

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#127]
As an admin, I'd like to minimise the risk of bots creating fake/malicious/spam venue listings, and to abuse the "nominate a venue" form. Open to DWYL ideas on how to do this, but I think a ReCaptcha on the forms would be easiest? We already have an account at Google if it's needed (used on our websites for various things)

**Acceptance criteria**
- [ ] The "list a venue" form has robust protection against bots creating listings
- [ ] The "nominate a venue" form has robust protection against bots sending in submissions
- [ ] If there are any other public forms on the site, they have the same protection too

**Comment by nelsonic** [comment]
@jussi-club-soda considering the fact that the Venue creation form has several "required" fields and bots don't usually cope well with this, I would _suggest_ that you "hold off" with adding a ReCaptcha until you see 20+ "spam" venue submissions in "production". (_i.e. delay this feature till you feel the "pain"_)

Meanwhile we will focus on the "Admin" side of the Venue Creation workflow to help the CS team 
review new venue submissions (_and updates to existing venues_) in a streamlined way,
so that if we see spam content we can easily flag and remove it.

Not saying that spam is not a problem. We know it well. see: https://github.com/dwyl/contact/issues/6
Just that using Captchas to protect against Spam is becoming less effective ... 
and often ends up _frustrating_ real users.

**Comment by iteles** [comment]
@jussi-club-soda We haven't seen any issues with this so far I believe?
Is it still a requirement?

**Comment by jussi-club-soda** [comment]
I don't think there have been any problems @iteles 

For the future - I guess it's not too complicated to add something if it does become an issue?

**Comment by nelsonic** [comment]
@jussi-club-soda It's very easy to add this functionality. 
ReCaptcha specifically is only a few lines of code to add it to forms, 
we try to avoid it for as long as possible because it just annoys the _real_ users.
