### ISSUE TITLE
Search by venue name

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#130]
As a customer on the venues page,
I'd like to search for a venue by name,
so I can find the specific venue I'm interested in

(does for venues what #44 does for drinks)

**Comment by iteles** [comment]
@SimonLab Before this is ready for testing, we need to:
+ Move the Search above the filters, lengthening the field
+ Make sure it looks good on mobile
+ Add documentation because @jussi-club-soda will need to know what to test for, similar to https://github.com/club-soda/club-soda-guide/issues/44#issuecomment-444445513

**Comment by SimonLab** [comment]
Searching a venues containing "London" in their names:
![image](https://user-images.githubusercontent.com/6057298/49628521-6d7f9800-f9dc-11e8-9a38-5d62f4873d5e.png)

**Comment by jussi-club-soda** [comment]
Thinks this can be closed now, you've got the documentation covered elsewhere?
