### ISSUE TITLE
Displaying the homepage search bar results

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#135]
Outcome from #133 & #134 

When search results are returned to the user, they want to see relevant information. The Club Soda initial view on this is:

+ [x] Search bar containing the term searched for is displayed at the top of the page
+ [x] Drinks are displayed under the title 'Drinks'
+ [x] Display a maximum of ~three~ four (1 row of) drinks that match the search criteria
  + [x] Drinks cards are as per #106 
+ [x] Follow the displayed drinks with an option of seeing more if there are more to display
  + [x] This link takes the customer to the drinks page with the search results for drinks
+ [x] After the drinks, display a maximum of ~three~ four (1 row of) venues that match the search criteria
+ [x] Venues are displayed under the title 'Venues'
+ [x] Follow the displayed venues with an option of seeing more if there are more to display
  + [x] Venues cards are as per https://github.com/club-soda/club-soda-guide/issues/122
  + [x] This link takes the customer to the venues page with the search results according to the term entered
+ [x] Customers can use the search bar at the top of the page to search for a different term
+ [x] Styling!

NB. No filters to be displayed on 'all' search page (drinks and venues) just the search bar.
NB2. Search criteria itself is in #133

**Comment by Cleop** [comment]
I've done a quick sketch of how the results page might look taking inspiration from other organisations search result display when dealing with different result types.

- At the top is the search input field (the same as we currently see on the Drinks or Venues pages).
- Underneath that we could display filters but only those that are relevant for both drinks and venues. I don't think there currently are any, but this is a concept more than anything else!
- Then there are 2 sections, one for drinks, the other for venues. Each section has a small title above it followed by the drinks cards or venue cards that we're already familiar with. Underneath each section there is a link saying 'See all' or 'Show all'. Clicking on this link could either take the user to the search specifically for that area e.g. drinks or venues and then it would display all the results on that page. Or clicking on that link could display all of the other results on the page they're on. From a technical perspective I think the first of these would be easier to implement. From a user perspective I think it's hard to say which is a better experience. I think it depends on how many hidden results there are to display!

![img_0115](https://user-images.githubusercontent.com/16775804/49727703-d11df580-fc68-11e8-8375-89d3d7045ddd.jpg)

Finally, a note to say that Harry provided an alternative view of the venue cards on his work on results. However this may just have been him experimenting. I'm not sure that his altered version offers much that our existing one does (especially as we've not done the location distance work yet). Plus I think it's helpful for users to be able to see the results without having to scroll too much and his alternative venue card takes up a row per card so would require more scrolling. Also, users may prefer the familiarity of the venue card design convention rather than having to get accustomed to another way of displaying something they've already seen before.
![image](https://user-images.githubusercontent.com/16775804/49727751-ef83f100-fc68-11e8-835b-c82163679843.png)

I'd be interested to know what kind of terms we think are likely to match on both drinks and venues given that currently venues only match by name. I used the example of 'brew' because I know brewdog has it in the name. But I can't think of many examples where a drink name/description key word is likely to be in a venue title.

**Comment by Cleop** [comment]
@jussi-club-soda - I noticed you suggested a maximum of 3 venue/drinks results. Given that the site currently displays these in rows with 4 to a row, would you be happy to revise this number to 4 for neatness?

**Comment by iteles** [comment]
@Cleop Whilst you were away, we agreed to simplify and use one design for the venue cards across the board: https://github.com/club-soda/club-soda-guide/issues/122#issuecomment-432584514

The other thing to consider here is the mobile view - how can we let customers know that venues are available if they only see drinks when they land on the page and start scrolling?

**Comment by Cleop** [comment]
Thanks for the clarification re venue UI 👍 

Good point re mobile view. I'll take a look at the other sites I was using for inspiration.

Regarding searches, I tried your 5 suggestions on venues but of them, the only one to match any of those terms was 'Ale':
![image](https://user-images.githubusercontent.com/16775804/49736453-17cc1980-fc82-11e8-9dc5-2e2f94c28471.png)

It appears that partial word searches may already be in use here as the 'Princess of Wales' shows up...

I'm not suggesting a combined search isn't necessarily useful but the fact we're struggling to come up with searches that match both just makes me wonder if we're searching/matching on the right things.

**Comment by SimonLab** [comment]
From the home page:
![image](https://user-images.githubusercontent.com/6057298/49894089-f5362e00-fe44-11e8-9317-d4b0c2f319f7.png)

then:
![image](https://user-images.githubusercontent.com/6057298/49894116-097a2b00-fe45-11e8-95e7-19c2ecb14651.png)

**Comment by Cleop** [comment]
![image](https://user-images.githubusercontent.com/16775804/50095932-752a1280-020e-11e9-93c0-f075ff2a76ea.png)

**Comment by iteles** [comment]
@Cleop A tiny thing: the search button on the homepage should be Club Soda pink please!
