### ISSUE TITLE
Order venue results by distance

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#22]
As a customer viewing my search results,
I'd like to order the results by distance,
so I can see the venues closest to the location I searched by

**Comment by iteles** [comment]
Whilst this is not in scope, I still want to note the following as it's on my mind:
This issue needs a little more thought around the user flow.
Due to GDPR, location can be considered personal data (see https://www.business.com/articles/gdpr-and-geolocation-data/) and we'd need to somehow integrate an _opt-in_ consent process here.

Whereas with 'Use my location' in the search bar #231 the consent is very clear and the user has to specifically click that link in order to have their data used (thereby providing consent, which you can also add a section in your Terms and Conditions to explain further), by simply ordering venues by distance from a customer, you are using their location data without consent.

One way to do this might be to add a cookie if they have already used the 'Use my location' option (storing a true/false value rather than the location itself perhaps) which we can check for and if so we can display venues ordered by distance. If not, then order them by CS score as per #23 . Currently we don't _store_ any location data, only utilise it on-click for the searches to be carried out.
