### ISSUE TITLE
Implement the 'Add a product' UI for Venues

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#233]
As a venue adding my stock
I would like to see a designed interface
so adding each drink I sell is engaging and seamless

## Acceptance Criteria 
- [ ] Implement 'adding a product' wireframes designed by @harrygfox for the add a drink process

## Screenshots

[AddProduct-compressed.pdf](https://github.com/club-soda/club-soda-guide/files/2676228/AddProduct-compressed.pdf)

**Comment by iteles** [comment]
@ctrembath As I mentioned almost as the last point in https://github.com/club-soda/club-soda-guide/issues/230#issuecomment-447067445 (which was just now, so you won't have had a chance to see it yet), this was discussed at length in our demo call because we had a lot of questions on how this UI would work for _multiple_ drinks and in practical terms. We came to the conclusion that this needed a lot of simplification in order to be not only seamless but practical and time efficient for venues (in a way that would encourage them to add their full stock list), see: https://github.com/club-soda/club-soda-guide/issues/92#issuecomment-427169853

**Comment by ctrembath** [comment]
@iteles ok - thanks for the update.

I will close the issue.
