### ISSUE TITLE
Drinks have disappeared | Make ABV a compulsory field

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#247]
Can't see any drinks in any view at the moment - home page carousel and the drinks view are all blank.

**Comment by iteles** [comment]
@jussi-club-soda My apologies, I've only just seen this as I've been out all day and @Cleop and @RobStallion have been head-down in their issues. **We'll make it our highest priority in the morning.**

I did a little digging and the drinks still in the database: https://www.clubsodaguide.com/admin/drinks
and appearing linked to brands: https://www.clubsodaguide.com/brands/7e798eee-a85d-483d-979e-2ef3f4757393
as well as linked to venues: https://www.clubsodaguide.com/venues/3a2d4887-826b-46de-87fa-12989c83659c

It's only in the homepage carousel and search page that they are not appearing.

**Comment by RobStallion** [comment]
![image](https://user-images.githubusercontent.com/15571853/50151560-29807300-02b9-11e9-947d-8e2a8c9d9589.png)

I have looked at the heroku logs for production but there are no error messages saying why the drinks are not displaying. 

Next step is to clone the database and create an instance of it locally to see if I can replicate this error on my own machine.

**Comment by RobStallion** [comment]
Cloned the database from production and ran it locally but it displayed the drinks 

<img src="https://user-images.githubusercontent.com/15571853/50152129-c099fa80-02ba-11e9-9bd3-e626afa9ef35.png" width=500px />

I have a more recent version of master so next step is to pull the version of master that is currently on production to see if I can replicate the error.

**Comment by RobStallion** [comment]
Have managed to replicate the error...

![image](https://user-images.githubusercontent.com/15571853/50152636-13c07d00-02bc-11e9-8b71-96a354a6a278.png)

Next step is to look into the code to see what is causing this issue. As there is no error messages it doesn't appear to be some code that is breaking.

It appears as if either no data is being withdrawn from the db or the front end functions are for some reason filtering out the data that is being passed. 

Will first check if the drinks are being withdrawn from the db.

**Comment by RobStallion** [comment]
[This](https://github.com/club-soda/club-soda-guide/blob/master/assets/elm/DrinksCarousel.elm#L88-L92) is where the error is happening in the code.

Looking into what is causing this to fail now as it seems to be related to the values being returned from the database.

My reason for thinking this is because this issue only occurs with the versions of the app and db that are currently in production. If the app uses the current version in production with my local test db it works fine, if we have the latest version of the app and the current prod db it works fine as well.

Want to find out exactly what value is causing this error so that it doesn't happen again in the future.

**Comment by RobStallion** [comment]
![image](https://user-images.githubusercontent.com/15571853/50158544-51c59d00-02cc-11e9-9957-95bc75869ffc.png)

Issue is being caused by Grapefruit and Passion fruit having a `null` value for abv. This is causing the `drinkDecoder` in elm to fail as it expects a float here.

This appears to be because when this drink was created it was not given an `abv` value.

![image](https://user-images.githubusercontent.com/15571853/50158981-6c4c4600-02cd-11e9-872b-1e9abedeca79.png)

@jussi-club-soda Do all drinks need an `abv`? If so we can make this a required value (similar to the way name works).

I would recommend making `abv` a compulsory field.

**Comment by jussi-club-soda** [comment]
Good detective work @RobStallion ! :)

Happy to make abv a compulsory field.

I've fixed that one drink on the live site and all's working there again.
