### ISSUE TITLE
'&' character shouldn't appear as '&amp;' 

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#250]
As a customer viewing a venue page
I'd like to see the & character presented correctly
so I don't get confused by the extra characters.

## Acceptance Criteria
- [x] & character should be processed to display '&'

## Screenshot
![screenshot 2018-12-18 at 10 24 57](https://user-images.githubusercontent.com/8418748/50147936-339d7400-02af-11e9-93f2-f694b8d75fe7.png)

**Comment by Cleop** [comment]
**Understanding so far:**
- this only occurs on fields defined by a text area rather than string input fields e.g. titles display & correctly but the description does not.
- The problem occurs when the fields are sent to the DB (the DB is capable of storing them both correctly as & or incorrectly according to what it is sent).
