### ISSUE TITLE
Search bar should contain a 'Search' CTA button

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#258]
As a customer on the Drinks all page
I'd like to see a Search Button attached the Search Bar
so I can 'Search' on both mobile and desktop

## Acceptance Criteria
- [x] Clicking the 'Search' button submits my search

## Screenshot (from @harrygfox designs)
![screenshot 2018-12-18 at 11 31 43](https://user-images.githubusercontent.com/8418748/50151336-87608b00-02b8-11e9-9ce2-0e1f286ddbe0.png)

**Comment by Cleop** [comment]
The searching happens automatically as they type and so a CTA button might be confusing as it would not practically achieve anything? In fact it might confuse users that the results adjust automatically but there is also a button...

I think that users are used to seeing searches now without CTA buttons e.g. Google:
![image](https://user-images.githubusercontent.com/16775804/50153051-2edfbc80-02bd-11e9-9f8e-fff819c7fa22.png)

**Comment by ctrembath** [comment]
Ok, I understand.

In that case on mobile I think it needs to behave in the same way as Airbnb / Google - offering a 'Search' or 'Go' button on the bottom right of the keypad. (see screenshot)
![img_0694](https://user-images.githubusercontent.com/8418748/50153835-79facf00-02bf-11e9-82af-2d5ff6756180.PNG)
![img_0695](https://user-images.githubusercontent.com/8418748/50153837-79facf00-02bf-11e9-893e-5359d6673708.PNG)

**Comment by SimonLab** [comment]
The "search button" is shown on the main page because the input is part of a form which contains a submit button. A small enhancement on this page could be to change the type of the input from `text` to `search`, see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search

For the search pages (drinks and venues), as mentioned above the input search filter dynamically the list of results when the input text change. This is done with Elm and the input text is not part of a form, that's why the search/go button on mobile is not displayed.

A solution is to change the input text to a search input however the keyword is not automatically close when the button is clicked as the input has still the focus. We can then try to add an event listener on this button which will force the focus out of the input (I'm currently implementing/testing this solution)

Airbnb avoid this issue as it forces the user to select an item on the dropdown of citites, and the keyboard is still visible otherwise.

From a UX perspective I'm not sure what is the best approach, maybe on mobile we should avoid filtering dynamically and use a form?
