### ISSUE TITLE
Add footer to all pages

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#262]
As a customer browsing the Club Soda Guide
I'd like to see a footer at the bottom of every page
so the layout of the page is inline with other websites

## Acceptance Criteria
- [x] Footer containing key links should sit at the bottom of every page

## Screenshot (from @harrygfox wireframes)
![screenshot 2018-12-18 at 14 34 46](https://user-images.githubusercontent.com/8418748/50160825-18902b80-02d2-11e9-937c-56e925e793fe.png)

**Comment by Cleop** [comment]
@jussi-club-soda - for now links will be added when you create static pages e.g. Terms and Conditions. 

Please can you provide me with any links that should go in the footer that link to elsewhere? E.g. outside the site so I can hard code them? Or even links that are within the site but are not static pages? 

I can't tell whether the links in the screenshot are examples or the real deal...

I'm also trying to recreate the gradient/filter from the design (my version):
![image](https://user-images.githubusercontent.com/16775804/50219683-e3deab80-0387-11e9-9959-bef2cb8c77dd.png)


I don't want to spend ages on it because the fastest thing is for you to give me the image with the filter as you have it from your designs (this image/filter isn't in Harry's). Alternatively you may already be happy with what I have managed to recreate.

**Comment by ctrembath** [comment]
Looking good!

One thing is the Logo for the footer should be inline with wireframes:

![guide logo icon-transparent](https://user-images.githubusercontent.com/8418748/50279191-f7018200-0440-11e9-96c3-95ea4e86500f.png)
