### ISSUE TITLE
Venue page shows 'distance from me' detail

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#27]
As a customer on a venue page,
I'd like to see how far away I am from the venue,
so I know how long it will take me to get there

**Comment by iteles** [comment]
Similarly to https://github.com/club-soda/club-soda-guide/issues/22#issuecomment-461539907, although not in scope I wanted to raise an alert here for the GDPR considerations I mentioned above:

Whereas with 'Use my location' in the search bar #231 the consent is very clear and the user has to specifically click that link in order to have their data used (thereby providing consent, which you can also add a section in your Terms and Conditions to explain further), by simply going ahead and displaying the distance from your customer, you are using their location data without consent.

The UX of this issue will need to be rethought before it can be implemented in future 👍
