### ISSUE TITLE
"Franklin & Sons" search bug

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#290]
If you search for "Franklin & Sons" from the front page search bar, it finds the right drinks. But if you then click on "See all" drinks, it comes up with nothing (there is "Franklin%20" in the search box).

I suspect it's the special character in the name that causes this?

**Comment by iteles** [comment]
@jussi-club-soda It is, a space translates to `%20`, thanks for raising!

**Comment by SimonLab** [comment]
This is due to the way we are passing the search term to elm. This is done with a flag here:
https://github.com/club-soda/club-soda-guide/blob/b0d37b97c9fe689e524c29cad9653de49d1c8f0b/assets/js/search.js#L9-L10

I think we can simplify this by removing the function `getQueryParams` and instead letting Phoenix extract the correct value similar to https://github.com/club-soda/club-soda-guide/blob/b0d37b97c9fe689e524c29cad9653de49d1c8f0b/lib/cs_guide_web/controllers/search_all_controller.ex#L27
