### ISSUE TITLE
Claiming a venue listing

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#30]
As a customer visiting a venue page,
I'd like to click a 'claim this listing' CTA which opens a direct email to club soda,
so that I can retrieve login details and update my venue details

**Comment by jussi-club-soda** [comment]
To add a bit of info - there are currently some venues where we as admins have set up their listings (either to tempt them to sign up, or just to flag up great venues to the site users) - we may want to do this in future too. So it would be great to have a simple way for managers to take them over.
The best process for this one needs a bit of thinking... If venue manager has already signed up to the site, the admin could just approve claim on the admin panel?

**Comment by iteles** [comment]
Agreed in sprint 3 planning to entirely de-prioritise this for now. Manual process for launch: if anyone emails the CS team, the team will have access to change the email address of venues manually.

**Comment by nelsonic** [comment]
@jussi-club-soda we need to keep track of how many venues are created both by the Venue Manger 
and by a person who is _not_ the "Owner" (Venue Manager) to determine the priority of this functionality.
As discussed, we would _like_ to ["crowdsource"](https://en.wikipedia.org/wiki/Crowdsourcing) venue listings in order to accelerate adoption of the platform,
but we don't want random people to create "ghost" venues as this will not add much value to the platform.
We need to test how many venues are created in _general_ (_i.e. content creation completion_)
before we can re-prioritise _claiming_ a venue.

**Comment by iteles** [comment]
For reference, allowing venues to be created by non-venue managers :arrow_up: is contained within #80
