### ISSUE TITLE
Displaying number of AF cocktails at a venue

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#306]
Just checking whether this is still covered somewhere:

When displaying the venue profile page, currently the number of cocktails is not shown at all? (I think this was discussed on a call once but we never decided how to do it?). Anyway, can we do something fairly simple, like replacing the first drinks card with the same template but where the brand/drink name normally goes, it says "Alcohol free cocktails: " and then the number. Take out the ABV button and "More details" link. And if we could also change the gray default image from a bottle to a cocktail glass that would be wonderful! :)

## Acceptance Criteria
If a venue has alcohol free cocktails
+ [x] The first 'drinks' card on the venue page should display this cocktail image instead of a bottle: https://projects.invisionapp.com/d/main#/projects/prototypes/15083747/assets/174312497
+ [x] The 'Drink title' semi-transparent div should now read "Alcohol free cocktails:" followed by the number of AF cocktails that venue carries
+ [x] There should be no ABV tag
+ [x] There should be no 'More Details' link on this card (the section under the pink line should be blank)
+ [x] The card should not turn around when clicked (no action should take place when the card is clicked)

![image](https://user-images.githubusercontent.com/4185328/50844899-9ab8c080-1363-11e9-9724-37386b2abce8.png)

**Comment by Cleop** [comment]
@jussi-club-soda - this is what I've got:
![image](https://user-images.githubusercontent.com/16775804/51179914-d224f100-18be-11e9-806b-4a4226b0676e.png)

What do you think of the positioning of the cocktail image? I haven't put it behind the white box because the lines are quite thick and distracting from reading. Also, the image is wider and not as tall as a lot of the other drinks, so if position it higher up then you end up with more whitespace underneath which looks more prominent without the ABV label.

I'll pop this in please test once it's viewable on staging but please feel free to give me feedback prior to then based on this screenshot if you have any immediate thoughts.

**Comment by jussi-club-soda** [comment]
Looks good to me!

**Comment by iteles** [comment]
If we’re going for capital letters on each word for the other cards we might want to capitalise each word here for congruence @cleop? :)
