### ISSUE TITLE
Deployement to Production mid-afternoon?

### ISSUE THREAD

**Issue by SimonLab** [club-soda/club-soda-guide#332]
Good morning,
New features won't be added to the website as we won't have the time the test (and fix if necessary) before the presentation on Sunday. We will focus instead on fixing high priority issues and make sure the application is running well on production.
**With that in mind we are wondering if we could deploy the application in production (as all the PRs have been merge now) later this morning or early afternoon.** 
This will give us some more time to run scripts to update the structure of the database and to fix any issues (if any) with production. Once the database is ready this will also allow admins to apply any changes to the data.

@jussi-club-soda  @ctrembath let us now your thought, thanks

script to run:
- define slug for venues: https://github.com/club-soda/club-soda-guide/blob/master/priv/repo/add_venue_slug.exs
- create link for current types and styles https://github.com/club-soda/club-soda-guide/blob/master/priv/repo/drink_type_style.exs

@RobStallion @Danwhy @Cleop I think there is also the venue score to update and the lat/long, are this script run when the application start or do we need to do it manually? Any other steps?

**Comment by RobStallion** [comment]
@SimonLab the script to add lat/long values only needs to be run when new venues are added to the database via a csv file. The script can be found [here](https://github.com/club-soda/club-soda-guide/blob/master/priv/repo/add_lat_long_to_venue.exs)

**Comment by iteles** [comment]
@ctrembath @jussi-club-soda For reference, #333 is not a blocker for deployment to production as we have identified the script that caused it - it will need to be run manually in production after deployment and we will thoroughly test it beforehand so this issue is not a blocker.

**Comment by jussi-club-soda** [comment]
I'm testing a few things: 

Creating a static page - works fine
Editing the "Contact" page - fine
Editing the "FAQ" page - "internal server error" - it also looks to me like something keeps adding the unnecessary bits of code (eg </span><span></span><span>) to the page?

Deleting a duplicate venue  - "internal server error"
Changing a drink's type - "internal server error"

Searching venues near me - works, but several venues are missing the profile image, venue type, and the score cups (this is where I am: https://www.clubsodaguide.com/search/venues?ll=51.525517099999995,-0.058719600000000004) - this is odd since the same details are visible on the plain venue listings page...


@iteles @Danwhy @SimonLab

**Comment by SimonLab** [comment]
Delete venue error:
![image](https://user-images.githubusercontent.com/6057298/50994179-7dc2ef80-1513-11e9-9373-ce903170a7a6.png)

@jussi-club-soda I manage to delete the "beer" duplicate, which drink type have you tried to delete?

**Comment by SimonLab** [comment]
@jussi-club-soda I haven't manage to reproduce the error for "Changing a drink's type - "internal server error""

I'm wondering if your session on the website is still valid. Could you try to reproduce this error and if it's still here could you add more details, thanks

**Comment by jussi-club-soda** [comment]
For example this drink:
https://www.clubsodaguide.com/admin/drinks/8883f3bd-f68b-4fe9-9c69-c1924d136cc6/edit

untick  soda (so there's only one style rather than two), click "Save" => "internal server error"

The rest of the team also reporting they can't upload any venue images. No error message, but images not uploading...

**Comment by iteles** [comment]
This was concluded, another one coming up soon 👍
