### ISSUE TITLE
Validation required: Venues shouldn't be able to add handle social link

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#344]
As a venue adding my social links
I'd like to see an error message if I try to add only my social handle
so that I know the link will only work with a full URL

## Acceptance Criteria
- [x] Social media links aren't saved unless they contain a full URL
- [x] Adding only the handle (@claretrem) publishes an error message telling me I need to submit the full url e.g. "http://instagram.com/claretrem"

## Screenshots
![screenshot 2019-01-10 at 13 40 14](https://user-images.githubusercontent.com/8418748/50971959-48031400-14dd-11e9-9697-b853941a30c3.png)

**Comment by Cleop** [comment]
- [ ] Run a script on existing venues that have provided the handle to convert it into a link

**Comment by Cleop** [comment]
I have been devising the script and come across a handful of hurdles which I have solving in turn:
- Creating url types for fb/twitter/instagram and then trying to update venues/brands currently with handles instead of urls exposed that some of those venues/brands also don't have validated website urls for their 'website' field as well. So then I created a condition to add a `www.` or `http://` to the websites as that seemed to be the validation issue.
- Then it became apparent that some of these venues/brands also did not have validated postcodes or slugs. I'm going to discuss with @Danwhy how he's managed to successfully upload these venues given that these fields are required.
- And finally I am experiencing an issue running the fn I am using to update Venues for Brands as I am getting this error:

![image](https://user-images.githubusercontent.com/16775804/51397192-98f7b580-1b38-11e9-9a63-6cacdad66749.png)

I'm not sure why the two update functions would be working differently.

**Comment by Cleop** [comment]
Tried to run the script on staging and got the following error:
![image](https://user-images.githubusercontent.com/16775804/51526101-85df3100-1e29-11e9-851d-3c02387586b4.png)

**Comment by Cleop** [comment]
On further investigation it transpires that this is due to:
>Why am I getting the postgres error "PGError: ERROR: permission denied for relation"

> Heroku Postgres hobby tier databases have row limits enforced. When you are over your row limit and attempt to insert data you will see this error. Upgrade to a production tier database to remove this constraint or reduce the number of total rows.

https://help.heroku.com/AVPS2TRA/why-am-i-getting-the-postgres-error-sql_error_code-00000-in-my-logs

**Comment by ctrembath** [comment]
@Cleop see #415
