### ISSUE TITLE
Related products should show at the bottom of a brand page

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#349]
As a customer viewing a brands page
I'd like to see 'Related Products' at the bottom of the page
So I can continue to discover low/no alcohol drinks

## Acceptance Criteria
- [x] Brand pages should contain a 'Related Products' section
- [x] Related products should be of the same type as the brands products

## Screenshots
![screenshot 2019-01-10 at 14 10 34](https://user-images.githubusercontent.com/8418748/50973744-86023700-14e1-11e9-81a2-1de196886aa7.png)

## Question
@iteles this seems to have been missed out of all brand pages, OR is it within another card I've missed?

**Comment by Cleop** [comment]
@jussi-club-soda - assuming that related drinks should be from the most popular drink type of a brand's drinks (because they can have multiple drink types).

What should be done if the brand doesn't have any associated drink types? Then should the related products section not display?

**Comment by jussi-club-soda** [comment]
Are there any brands with no type at all? If so, it's probably a database content issue we need to fix...

**Comment by iteles** [comment]
@ctrembath In answer to your question: this was never part of the original scope, but as we discussed with you during the design phase, we made sure Harry had free rein in the design to provide you with a full picture of what could be done in order to allow you to test potential new features with your users, have a more complete style guide to use in future and give you a fuller idea of what could be done. It hasn't been missed, it was simply part of Harry's fuller vision for the potential future, which we agreed would have been a shame to stunt given it was evolving at the time of design phase and didn't require much extra effort to document for you!

However, we're happy to add this in (as we’ve discussed, we’ve made additional time available to you at no extra cost for all of the additional scope) and there is a clear use case for it as well as being undoubtedly useful to Club Soda 👍

**Comment by Cleop** [comment]
Currently in the process of fixing a how to use the same drink card component as higher up on the page (using css only indexes to flip the cards) without duplicating the indexes.
