### ISSUE TITLE
Brand member page

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#351]
@iteles - I haven't had an opportunity to see what a page would look like if flagged the brand as a 'member'

Do you know to what level you will achieve the designs for the page? 
@jussi-club-soda explained to me that we are removing the insta-feed from this page. Will all other elements of the page be present?
At what point will I be able to test this out? 

## Design
![member brand](https://user-images.githubusercontent.com/8418748/50974218-a2eb3a00-14e2-11e9-9cae-dea6569fcce2.png)

**Comment by ctrembath** [comment]
@Cleop thanks for the update.

Can you explain what you mean by:
`Drink category or retailer category breaking down those sections`

**Comment by Cleop** [comment]
Retailer category e.g. online retailer
![image](https://user-images.githubusercontent.com/16775804/51030534-a25dac80-1591-11e9-8c6c-b4dd73398ae2.png)

Drink category e.g. beers
![image](https://user-images.githubusercontent.com/16775804/51030566-c1f4d500-1591-11e9-9b19-b1f650c233ab.png)

So far the reason why we're not including these is because there's not been enough variation to make these bits of text useful / providing added insight. If anything they just clutter up the UI and look bad if there's only one link per category. However if in the future user testing etc. were to reveal that these could benefit from some distinction/sorting we could consider implementing them.

**Comment by Cleop** [comment]
@ctrembath - can this issue be closed or are there any takeaway actions or issues that need to be created off the back of this?

**Comment by ctrembath** [comment]
@Cleop - i've been trying to update brand member content. On clicking on any of the links e.g. "add brand description" I am sent to a 404 page.

**Comment by Cleop** [comment]
example 404 endpoint from brands page: `brands/admin/Jever/edit`
example endpoint from brands dashboard that then works: `admin/brands/Jever/edit`

The admin and the brands are the wrong way around. I'll swap this.

**Comment by Cleop** [comment]
@ctrembath - thanks for spotting. This bug wasn't showing up locally. It's a capitalisation issue with the asset, I'll make that change.

**Comment by ctrembath** [comment]
Hi @Cleop - I'm still seeing this issue on Heineken

**Comment by ctrembath** [comment]
@Cleop - I seem to be seeing this across the whole platform now .. 

![screenshot 2019-02-04 at 11 02 52](https://user-images.githubusercontent.com/8418748/52204607-92717980-286c-11e9-880b-b0693732182c.png)

**Comment by Cleop** [comment]
**The twitter svg is not loading on staging:**
<img src="https://user-images.githubusercontent.com/16775804/52203581-83d59300-2869-11e9-902c-d7364efe6aec.png" width=300px />
https://club-soda-guide-staging.herokuapp.com/brands/Dalston%20Cola

**Despite the fact that it is loading locally:**
<img src="https://user-images.githubusercontent.com/16775804/52203611-9a7bea00-2869-11e9-918f-e63d27265f30.png" width=300px />

This is the code for it:
`            <img class="w-1-5rem dib pr2" src="<%= static_path(@conn, "/images/twitter.svg") %>" alt="Twitter icon">
`

The only thing of note is that I believe it was working and then I renamed it because it had a capital letter 'Twitter.svg' so I renamed it to be all lowercase and updated the code so that all code instances had the same name. Now no versions of it are working. I feel like I've experienced something before where sometimes if a file already exists and no changes to the file are made (apart from the name change) then the name doesn't update.

@SimonLab @Danwhy - do you have any suggestions?

**Comment by Danwhy** [comment]
@Cleop Yeah, git doesn't pay attention to case changes in file names if nothing else in the file has changed: https://github.com/club-soda/club-soda-guide/blob/master/assets/static/images/Twitter.svg

**Comment by Cleop** [comment]
This has now been resolved on both staging and production 🎉 

![image](https://user-images.githubusercontent.com/16775804/52423165-72052180-2aef-11e9-8cd1-2f9cf05b7a68.png)
