### ISSUE TITLE
Search Enhancements epic

### ISSUE THREAD

**Issue by SimonLab** [club-soda/club-soda-guide#378]
We have now a few issues related to how the search input on the main page should return the results:
- #133 text search on drinks and venues fields
- #274 postcode search which returns only the venues near the postcode
- #276 location search which returns only the venues near a location
- #342 Autocomplete search

We can see that a search type can be one of the three types: **text, postcode or location**.
So the first step is to determine the type of search:
- 1 We now have saved a list of postcodes in the memory of the application (using ETS see #129). We can then check if the search term match one of the postcode saved and if yes we can get the latitude and longitude of the postcode searched and find the nearest venues, similar to "use my location" logic. **For this to work the postcode search for needs to be the full format otherwise we can't get the latitude/longitude data (see https://en.wikipedia.org/wiki/Postcodes_in_the_United_Kingdom#Postcode_area for the postcode format)

- 2 If the search term doesn't match a postcode, the next step is to search by location. We could use the Google API to determine if a search term is matching a location however this might slow down the search as we will need to send a query first to Google, and it might also be costly, especially if we use an autocomplete see #342 
  - So I would suggest that we build and save a list of location with their latitude/longitude and like the postcodes we save this list in the application memory, @RobStallion do you think this would be possible?
  - Once we have the list of locations saved, we can apply the same logic used with the postcode: getting the latitutde/longitute then searching for near by venues. I think the difficulty here is to find/build the list, see below how we could get feedback from users

- 3 Finally if the search term doesn't match a postcode or a location we can trigger the "normal" text search (ie the current search logic)

After the result page is displayed we need a way to allow users to switch between the types of search. For example a user might want to find the venue matching exactly a postcode but doesn't want to search for the venues near this postcode. So instead of triggering the "postcode search" the application should have used the "text search". To allow user to specify the type of search we could have a link on top of the result page similar to:
 
- "Venues near the postcode {postcode} is not what you are looking for? Search venues matching exactly this postcode instead? link_to_search_by_text"

- "Venues near the location {location} is not what you are looking for? Search venues matching the search term instead? link_to_search_by_text"

Getting feedback from user if a search term should be a postcode or a location:
- "The search term doesn't return the expected venues? Tell us if the search {search_term} is a postcode or a location and we will add it to our list of postcode and location, link_to_send_feedback"

@nelsonic @iteles @RobStallion this is my thought how we could search on different types. I think searching by postcode should by relatively easy. However the search by location might take a be more time as we need to create a list of location first.
Does this steps make sense, do you have any other ideas on this?

**Comment by jussi-club-soda** [comment]
Hi, some quick thoughts on this. A very good issue to raise - search by venue location has come up as the number 1 topic in our feedback so far.

What Simon suggests above may be too complex. What people have been saying they would like to see is the ability to search for venues based on:

a) first part of the postcode - so I can find a venue in Stratford by searching for "E15"

b) city/town - so I can find a venue in Cambridge without knowing what the postcodes there are - just search for "Cambridge"

Without full technical understanding, I wonder would a text-based search through all the relevant fields (venue name, all address fields, description etc) on the database do this?

Simon's thinking would be amazing to have, but not worth the effort (at least not yet)? People are quite happy with simple tools - plus we have the full "search near me" for when you want to find something locally.

**Comment by SimonLab** [comment]
Thanks for your feedback @jussi-club-soda :+1:  and it's good to know that search by location is one of the most wanted feature.

We have now search by postcode which is deployed on staging, so if you search for a postcode it will show all the venues near this location. However the format of the postcode needs to be the most detailed one for this feature.
We can indeed also add the postcode in the text search.

For the location name my only worry is that the address field of the venue is not required (and not validated, ie the value can be anything):
![image](https://user-images.githubusercontent.com/6057298/51334438-b31d8f00-1a77-11e9-9923-ee767385c295.png)
I'll add the address of the venue in the text search too but it might not return the expected values

I'm currently working for a solution to be able to match a location name to a longitude/latitude which will allow us to find the venues around this location

**Comment by RobStallion** [comment]
@SimonLab I have been looking into ways of searching, filtering a cache by partial/sub strings but it is proving to be trickier than I would have thought.

ets is incredibly fast when it comes to exact matches, but it doesn't handle partial matches quite the same way.

From what I have seen, it appears that in order to filter the ets table by a partial match you need to be able to put the logic in a guard clause. For example...

```elixir
iex(1)> :ets.new :test, [:named_table]
:test
iex(2)> :ets.insert :test, [{1}, {2}, {3}, {4}, {5}]
true
iex(3)> f = :ets.fun2ms fn({n}) when n < 4 -> n end
[{{:"$1"}, [{:<, :"$1", 4}], [:"$1"]}]
iex(4)> :ets.select :test, f
[1, 3, 2]
```

the `:ets.fun2ms/1` function helps to create a list that can be passed into the `:ets.select/2` function to filter the table. As you can tell this is saying select all elements that are less than 4, and that's what the select function returns. 

This becomes an issue however when we try to match on partial strings, like a part of a postcode or address. This is because there is no way to match partial strings with a guard clause (that I know of anyway). 

To search/filter the cache by string we could use the `:ets.foldl` function...

```elixir
iex(1)> :ets.new :postcodes, [:named_table]
:postcodes
iex(2)> :ets.insert :postcodes, [{"n16pj"}, {"e20sy"}, {"e28as"}, {"e84da"}]
true
iex(3)> :ets.foldl(fn
...(3)>   {<<"e2", _rest::binary>>} = postcode, acc -> [postcode | acc]
...(3)>   _, acc -> acc
...(3)> end, [], :postcodes)
[{"e28as"}, {"e20sy"}]
```

As you can see this returns all the postcodes starting with e2. The problem with this though is that it relies on pattern matching on the string with binary, `<<"e2", _rest::binary>>`, and we cannot pass variables into this (e.g. `<<"#{some_variable}", _rest::binary>>` is not valid syntax). 

There are work arounds that I can think of, but no direct solution.

One way around this could be to store the first part of the postcode in the cache with a shortened version of the lat and long (e.g. {e15, 51.5413, 0.0059} would/could be stored in the cache for E15). 

For the location search, I think your plan on making it work similar to the postcode search will work well (user types in area name, we search cache, get lat-long value, use lat-long value to get venues by distance).

With regards to #342, Autocomplete search, I think that this will be the trickiest part. As we cannot easily query the ets cache for substrings, one solution I have thought of it to make many different ets tables (for example, one for each letter of the alphabet). We could then store all location, address info in these tables (the same way you mention in point 2 [here](https://github.com/club-soda/club-soda-guide/issues/378#issue-399838675)). The reason this could help with autocomplete though is that if we need to pass the entire list to the front end, for elm to filter as the user types and return possible matches, then this will significantly reduce the size of the data that elm would need to process. 

I think this would need to be tested some but could be a solution for the autocomplete.

**Comment by RobStallion** [comment]
@SimonLab Just noticed a small issue with the text search now.

In the SearchAllController [here](https://github.com/club-soda/club-soda-guide/blob/master/lib/cs_guide_web/controllers/search_all_controller.ex#L9) you call the check_or_cache function. This function makes an api request if the term is not in the cache. This means that even if you search for a term like "beer" it is making an api request to check if it is a real postcode. 

The way I avoided this when I was checking if a postcode was valid is by first using the `Fields.Postcode` type to check if the string matched a postcode in format. If it does, then I check to see if it is a correct postcode. See [here](https://github.com/club-soda/club-soda-guide/blob/master/lib/cs_guide/resources/venue.ex#L268). 

I think we should implement something similar in the search all action to avoid unnecessary api calls.

**Comment by SimonLab** [comment]
Closing this epic as the search logic has now been implemented following the suggestion https://github.com/club-soda/club-soda-guide/issues/378#issuecomment-455219398
