### ISSUE TITLE
AWS account migration

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#421]
Have now managed to reactivate our AWS account. What's next, do I invite someone to be a user of our account (or something else)?

@iteles @Cleop ?

**Comment by jussi-club-soda** [comment]
Thanks @nelsonic - I agree about AWS, it's not the easiest interface to work with...

@Cleop have just emailed you the password - let's hope it all works!

**Comment by Cleop** [comment]
https://aws.amazon.com/premiumsupport/knowledge-center/account-transfer-s3/
> You can't transfer Amazon S3 resources between AWS accounts. Instead, you can copy Amazon S3 objects from one account to another so that you give ownership of the copied objects to the destination account. 

@SimonLab @Danwhy @RobStallion @nelsonic - @nelsonic assigned 25mins to this issue and I have already spent more than that and I still feel like I do not understand what I need to do to complete this issue. 

@jussi-club-soda has shared a password with me but no other details of his bucket. I tried logging in with my email and the password but it failed, so I am only able to log in with my existing password. 

I have been researching but been overwhelmed by the number of AWS articles along the subject but that all seem to be different:
- https://stackoverflow.com/questions/29822570/how-to-transfer-an-amazon-s3-bucket-to-another-account
- https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_policy-examples.html
- https://aws.amazon.com/premiumsupport/knowledge-center/copy-s3-objects-account/
- https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html

and the one @nelsonic shared above: https://docs.aws.amazon.com/AmazonS3/latest/dev/example-walkthroughs-managing-access-example1.html#grant-permissions-to-user-in-your-account-step1

I am confident that I can solve this if I put more time in to reading through these articles but given that I am over the estimate I wanted to ask if anyone else could simplify or point me more directly along the right path so I am not going wayward from the time estimate.

**Comment by nelsonic** [comment]
@Danwhy you have decent XP in AWS please remote-pair with Cleo on getting the S3 objects down/uploaded. e.g: use https://cyberduck.io/ to drag-n-drop the files to desktop and then back into the new (CS-controlled) bucket in "bulk". This is a one-off task so no need to script it.

**Comment by Cleop** [comment]
@jussi-club-soda - I have the password you sent me but I believe I'm missing a couple of other details in order to complete the process.

I haven't received a notification email from AWS so I need you to share these with me if you can:

- the 'IAM User Sign-In URL'
- a username for me

See this article on where to find those details:

https://docs.aws.amazon.com/IAM/latest/UserGuide/getting-started_how-users-sign-in.html

**Comment by jussi-club-soda** [comment]
IAM users sign-in link: https://club-soda.signin.aws.amazon.com/console
username: Cleo

**Comment by Cleop** [comment]
Thanks @jussi-club-soda - the last two details I will need are: 

- AWS ACCESS KEY ID
- AWS SECRET ACCESS KEY

Please share them with me privately.

**Comment by jussi-club-soda** [comment]
I will email them to you in 2 separate emails!

**Comment by nelsonic** [comment]
@jussi-club-soda thank you for communicating the keys with Cleo.
Sadly email is not a _secure_ means for communicating the keys.
A more effective way is for Jussi to update the Environment Variable on Heroku _directly_.

**Comment by Cleop** [comment]
You can do this for staging **but not for production yet** (as the production images are still in the process of uploading):

In heroku go to settings:
![image](https://user-images.githubusercontent.com/16775804/51978501-45636100-2482-11e9-84f8-d15fb9e43167.png)
Where you will see 'config vars', you can update the values for the AWS ACCESS KEY ID and the AWS SECRET ACCESS KEY with your new ones. Then save them and that's it!

**Comment by nelsonic** [comment]
@jussi-club-soda It's not a "problem". Email is _generally_ "safe". But in the same way that you wouldn't email someone a Bank/PayPal password, you wouldn't do it for an AWS Key because a "bad" hacker will have a _fast_ way of finding the keys if they ever gained access to the email system. 
We tend to treat email as a "postcard" that the mail man (_and all his mates at the pub_) can read.
Unless both you  and your recipient are using an "encrypted" email service like [ProtonMail](https://www.makeuseof.com/tag/3-secure-encrypted-email-providers-online/) email is not "secure".

As for the instructions for how to upload the keys to Heroku 
please see: https://github.com/dwyl/learn-environment-variables#environment-variables-on-heroku
(_here's one we made earlier..._)

**Comment by Cleop** [comment]
The uploads to the staging and production buckets are now complete 🎉 I've also checked and added any files that were added after the upload began and manually added them. 

So now @jussi-club-soda all that remains to be done is to change the env variables as outlined above on both the staging and production heroku accounts.

Please let me know once you've done this or if you need any assistance with it.

**Comment by iteles** [comment]
@jussi-club-soda I suggest you test this on staging first 😊

**Comment by jussi-club-soda** [comment]
Do I have access to the staging Heroku dashboard? @iteles can you check please?

**Comment by iteles** [comment]
@jussi-club-soda You should have an email inviting you as a collaborator in your inbox, freshly sent 😊

**Comment by jussi-club-soda** [comment]
Got it! Have updated on staging, fingers crossed all is well still :)

**Comment by Cleop** [comment]
Images appear to still be displaying on staging but I'm not able to upload a new one:
![image](https://user-images.githubusercontent.com/16775804/52065676-ef201c00-256e-11e9-8eda-6ea22ae80a56.png)
@Danwhy - I looked on heroku and appears that @jussi-club-soda hasn't updated the bucket name, so I then updated the bucket name but then all of the images that were appearing were no longer appearing. However when I uploaded the bucket name the image uploading functionality was working... (I have since changed the bucket name back to the old name so that the images still appear on staging, but uploading won't be working)

So something's not quite right... any ideas @Danwhy ?

To confirm @jussi-club-soda - you updated the AWS ACCESS KEY ID and AWS SECRET ACCESS KEY values on heroku on staging?

**Comment by jussi-club-soda** [comment]
@Cleop yes, those two, with the newly created values (not the first set I emailed to you).

**Comment by Danwhy** [comment]
The access keys should only be used for uploading so if that's working when the bucket name is correct, I would guess they are fine.

It sounds like it might be a public access issue if we an upload but can't see them, so we should make sure the permissions for viewing images is right

**Comment by Cleop** [comment]
@Danwhy - from what I can see, the access settings are the same on the old bucket and the new one. Perhaps we can pair on this together after stand up this morning?

**Comment by Cleop** [comment]
Issue resolved, the images that were breaking were ones that had been added/changed since the upload took place. All of the other images are fine.

@jussi-club-soda you can now go ahead and change the env variables on production too, just make sure you change the bucket name env var as well to: 'club-soda-prod'

**Comment by jussi-club-soda** [comment]
hi, have just changed the AWS variables, and no images are loading - does it just take a while to update?

@Cleop ?

**Comment by Cleop** [comment]
Thanks for letting us know @jussi-club-soda - I'll take a look at what's happening now.

**Comment by Cleop** [comment]
I've tweaked one of the settings and the vast majority of images now seem to be showing 👍 . I'll check if any broken ones are ones that are new since the data duplication was done.

**Comment by Danwhy** [comment]
I think the few left that aren't showing is just due to caching. Some of them are missing, then starting to show for me after a few refreshes

**Comment by jussi-club-soda** [comment]
yep, showing up here as well now :)

**Comment by Cleop** [comment]
I've added the most recently added S3 files from the other bucket. @jussi-club-soda if you'd like to test now and let me know if you spot anything not looking right but otherwise we can close this issue and perhaps in a few days I will close the old account.

**Comment by Cleop** [comment]
I've fixed all of the errors on drinks/venues and there are now only 4 fewer photos on the new bucket compared to the old bucket.  I can't locate where those are, my guess is that they are old images that are no longer displayed/used hence why there are no errors for them. From what I can see by looking at the production DB, there are no brand images on production. 

So @jussi-club-soda if you'd like to test and if you do come across any more broken images please let me know.
