### ISSUE TITLE
Search by drink name

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#44]
As a customer on the drinks page,
I'd like to search for a drink by name,
so I can find the specific drink I'm interested in

**Comment by jussi-club-soda** [comment]
Does this also include text search on the descriptions on the drinks page? Could be a good idea?

**Comment by iteles** [comment]
@SimonLab We need to:
+ Move the Search above the filters
+ Make sure it looks good on mobile
+ Add documentation because @jussi-club-soda will need to know what to test for,  e.g. a search for 'Cola' returns `Ariel Cabernet Sauvignon` amongst the Colas:
![image](https://user-images.githubusercontent.com/4185328/49509285-c7694c00-f87c-11e8-8762-878510f33227.png)


![image](https://user-images.githubusercontent.com/4185328/49509185-82ddb080-f87c-11e8-9282-1f6d3d7b8e24.png)

**Comment by Cleop** [comment]
Styling/ordering amended

![image](https://user-images.githubusercontent.com/16775804/49526894-ad456300-f8a8-11e8-89fa-3b65ecda3767.png)

![image](https://user-images.githubusercontent.com/16775804/49526909-b5050780-f8a8-11e8-9a4d-7742d21d25f8.png)

**Comment by SimonLab** [comment]
Searching drinks with the term "beer":
![image](https://user-images.githubusercontent.com/6057298/49628671-77ee6180-f9dd-11e8-8946-300c0c5e91e4.png)

**Comment by jussi-club-soda** [comment]
As with venue search, all good, documentation covered elsewhere!
