### ISSUE TITLE
Store all homepage search queries

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#445]
As a admin viewing the admin page
I'd like to see a page that shows me all homepage search terms,
So I can have a clear idea of how people are using the search bar.

## Acceptance Criteria
- [x] Storing all homepage search queries
- [x] Admins are able to view search queries
- [x] Admins are able to download search queries (CSV)

**Comment by SimonLab** [comment]
We could create a new specific table in Postgres to log any searches or click on "venues near me" from the home page (which other information do we want to save, timestamps, user agent or other http headers from the requests?). This implementation could be done relatively quickly.

Another solution would be to use the "ATM" tool from our stack as soon as it is ready:
![image](https://user-images.githubusercontent.com/6057298/52556561-d7edf380-2de4-11e9-97c1-ac628ec4d6c2.png)

**Comment by iteles** [comment]
@SimonLab 👍 
For now let's begin with a simple table that logs search terms and their timestamp 😊

**Comment by nelsonic** [comment]
@SimonLab if we can update **`alog`** to use CIDs then we can get a Beta of ATM ready in 1 day.
It's _really_ simple. The ATM schema is: "Events"
+ **`inserted_at`**
+ **`name`**: e.g: "search"
+ **`detail`**: e.g: "Brewdog 0%" or "E2 0SY"
+ **`data`** e.g: `{"location": "/"}` (_any extra data we want to put into the event for later analysis_)
+ **`cid`** (_used so that we can refer to a specific event
+ **`session_id`**: the session ID of the client/device that created the event. 
  + **`session_id`** will allow us to correlate any event in ATM to a session so that the journey is traceable. E.g: arrived on home page, searched for "Brewdog 0%", clicked on `/brew-dog` ... etc.

**Comment by SimonLab** [comment]
Admin page now display at the bottom of the page a new link to see and download the searches log:
![image](https://user-images.githubusercontent.com/6057298/55220312-e0688500-51fe-11e9-936f-6bbc26072ec4.png)

When clicked on the link the table with all the log is displayed (I'll reorder the list to show the most recent search at the top)
![image](https://user-images.githubusercontent.com/6057298/55220356-fece8080-51fe-11e9-9ac6-99f3c14fca8b.png)
