### ISSUE TITLE
Homepage view on Android mobile device

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#446]
As a user using a Huawei p9 Lite,
I'd like to the hero area copy displayed correctly
so the Club Soda Guide looks legitimate

## Acceptance Criteria
- [x] Dropdown menu shouldn't show the top of 'hero text'
- [x] Hero text should have spacing to ensure hero section doesn't look so cramped

## Screenshots
<img src="https://user-images.githubusercontent.com/8418748/52210385-d9686a80-287e-11e9-9c68-de4f1321fb8e.png" width=300px />
<img src="https://user-images.githubusercontent.com/8418748/52210437-0ae13600-287f-11e9-9d20-f80e6003c85f.png" width=300px />

**Comment by iteles** [comment]
@ctrembath Having the navigation menu to open over the homepage without touching or pushing down the content is a very standard user pattern but you usually don't notice it because menus can be very long and take up the entire page (see amazon.co.uk or airnbn.com for example).

We could give the menu a little more padding at the top and then eventually it could also cover the entire screen if users feel this is problematic 👍

**Comment by Cleop** [comment]
**Note to self:**
- [ ] Add `pt6 pt0-ns` to text

**Comment by Cleop** [comment]
<img src="https://user-images.githubusercontent.com/16775804/52557117-6a42c700-2de6-11e9-8bf6-37f1ab0859f6.png" width=250px />
<img src="https://user-images.githubusercontent.com/16775804/52557125-6f077b00-2de6-11e9-9d6e-8b38697c0f6e.png" width=250px />
