### ISSUE TITLE
Selecting a drink takes you to the brand page

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#46]
As a customer on the drinks page,
I'd like to select a drink and be taken to the relevant brand page,
so I can see details of the product & brand

**Comment by iteles** [comment]
Enhancement to #106, highest priority addition, as per https://github.com/club-soda/club-soda-guide/issues/32#issuecomment-419108434

**Comment by iteles** [comment]
This isn't working quite right yet. All drinks take a customer to a hard-coded URL `/brands/d.brand.entry_id` rather than to the actual brand.

### Steps to recreate bug:
Clicking on 'More Details' on the `Gusto Cherry Cola` card on the landing page and then clicking on the brand name on the card:
![image](https://user-images.githubusercontent.com/4185328/49041561-7e9afe80-f1bd-11e8-9b90-30d4c602d23f.png)

Takes the customer to: https://club-soda-guide-staging.herokuapp.com/brands/d.brand.entry_id
![image](https://user-images.githubusercontent.com/4185328/49041589-8b1f5700-f1bd-11e8-8d32-e0e5ff1ec13e.png)
