### ISSUE TITLE
Brand pages display links to online retailers, shops and wholesalers

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#49]
As a customer on a brand page,
I'd like to see links to online retailers, shops and wholesalers,
so I know where I can buy the drinks

**Comment by Cleop** [comment]
@jussi-club-soda - what details would you like to be included for retailers? My guess is:
- name
- website

For reference in addition to name and website, other venues have:
- postcode, image, CS score
But my assumption is these are not wanted for online retailers?

If you could confirm which details you would like and then we can think about how to style/display them.

**Comment by Cleop** [comment]
**Technical note:**

`<a class="f6 lh6 cs-mid-blue underline dib v-top" href="https://<%= venue.website %>">`

Currently I'm hard coding in a 'https:// because when I don't the link takes you to an internal site page not an external site. However we will need to ensure that websites are either not added with the 'https' or that we create a case to handle this so they don't error.

**Comment by Cleop** [comment]
@iteles - yes @Danwhy and I have spoken about this and what we propose is that in the documentation it is indicated that all external links must include a http or https beginning. Then we can  also add this as a requirement to fields so this is validated before a new retailer etc. is made.

**Comment by Cleop** [comment]
When an admin creates a new retailer, where should they be redirected to on completion of the action? The list of all retailers?

The reason why I ask is because for venues, when a new venue is created you get redirected to the view of the venue page. However, as retailers don't have the same information e.g. club soda score, image, description etc. I don't think this is helpful.

**Comment by iteles** [comment]
@Cleop List of all retailers definitely seems like the most intuitive place 😊 👍 
Let's go with that as a starting point and test.

**Comment by Cleop** [comment]
**Templates to make:**
- [x] Create a retailer form
- [x] Edit a retailer form
- [x] View all retailers list 
  - [ ] only displaying all venues of type 'retailers'
- [ ] Delete a retailer
- [ ] Ensure redirects all go to list of all retailers.

- [ ] Need to make sure type 'retailers' are excluded from the Venues page?

`https://www.amazon.co.uk/` for all instances of amazon **OR** 
Heineken amazon link:
`https://www.amazon.co.uk/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords=heineken+alcohol+free+beer&sprefix=heineken+%2Caps%2C160&crid=N5XCMG3WUXSS`
Budweiser amazon link:
`https://www.amazon.co.uk/s/ref=nb_sb_ss_i_1_13?url=search-alias%3Daps&field-keywords=budweiser+alcohol+free+beer&sprefix=budweiser+alc%2Caps%2C158&crid=1PK66VTJ9D7KU`

- [ ] remove postcode field as mandatory and make website field mandatory once @Danwhy has finished the work enabling us to use a different changeset.

- Currently Jussi has to add the brand to the retailer. Would it be easier to add the retailer to the brand? This wouldn't be possible though if retailers have a different link per brand e.g.

**Comment by jussi-club-soda** [comment]
I'll spend a bit of time over the weekend to think about all this...

**Comment by jussi-club-soda** [comment]
Ii think this could benefit from a discussion, there are a few questions to consider:

I like the idea of shops as "venues" from one point of view, but it does also have possible drawbacks

We need to remember that online shops are different from real world ones - we have affiliate links to the former (at least DryDrinker.com, wisebartender.co.uk and amazon.co.uk - these 3 are set up differently in the designs already?), and in an ideal world from a brand page we'd have direct links (with affiliate code in the URL) to the drink on the shop (i.e. not just to the front page of the shop). 

So there are a few moving parts here...

**Comment by Cleop** [comment]
At the moment @jussi-club-soda if you wanted retailers to have custom links per drink you'd have to create a 'new' retailer for each link. So you may have several 'amazon' retailers and in order to differentiate between them you'd have to name them differently (in a way that would look good with the UI for the link) e.g. 'Nix and Kix on Amazon' could be the whole retailer name as that's how the link would appear.

**Comment by jussi-club-soda** [comment]
Sorry @Cleop, I can't see what's going on here? I can create retailers, but how are they linked to brands?

**Comment by ctrembath** [comment]
This looks great.

Can we remove the titles if there are no Wholesale / Retail links (#416 ) ?

**Comment by iteles** [comment]
@ctrembath No problem, we’ll add that to the scope. Shall we close this issue and deal with that in #416?

**Comment by ctrembath** [comment]
@iteles good idea :)
