### ISSUE TITLE
Idea: brands listing

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#499]
A bit of user feedback we've had: we have listings pages (and top bar menu links for them etc) for drinks and venues, but not for brands. What if a user wants to browse brands instead? 

Just throwing this out for thoughts: how could we do this if we decided to add it to scope? 

I guess the simplest would be just a list of brand names with a link to their profile page (similar to the admin page). 

Next level up could be to list member brands first, maybe with their profile image, then all the non-members after that without an image. 

Any other ideas?

@iteles @nelsonic @Cleop @Danwhy

**Comment by Cleop** [comment]
So given that the feedback here is the ability to *browse by brands*, one alternative would be to edit our existing drinks page which already has the functionality for browsing by brands but improving the UI so that users are aware of this. As users can already search by brand on the drinks page and see brands displayed on drinks cards.

We could amend the searching copy to make it clear you can search by brands and see if we need to differentiate the brand name on the drink card. Or any other suggestions for improving this?

The reason why I ask is because I think a page with a list of brands on might look a bit dull and users may be disappointed if they can't search by brands as they can on the drinks page. I also think that we'd have to make it clear why certain brands appeared above others if we integrated the members concept because otherwise I'd find that confusing as a user, especially if I couldn't search. That's not to say this couldn't work but those are a couple of initial thoughts on things we'd have to take into consideration.

**Comment by iteles** [comment]
@jussi-club-soda Would the use case here be to be able to search by brands or to actively see  which brands carry AF or low alcohol drinks (without knowing which brands these are in advance)?
