### ISSUE TITLE
Brand profile pictures

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#501]
Looks like the brand profile pictures do things I wasn't expecting:

On a laptop screen the images get tiled

On mobile screen only the top left corner of the image is shown

(two examples: https://www.clubsodaguide.com/brands/heineken and https://www.clubsodaguide.com/brands/old-mout )

Is this a feature or a bug?

**Comment by nelsonic** [comment]
@jussi-club-soda thanks for creating this issue. ✅ 
If you are able to take a **screenshot** of both views, please do upload so we can visualise it. Thanks! ✨ 
instructions for taking screenshots on _any_ device, please see: https://www.take-a-screenshot.org

**Comment by jussi-club-soda** [comment]
<img width="960" alt="brand-laptop-view" src="https://user-images.githubusercontent.com/43003062/54428304-011bdf80-4715-11e9-858c-ec3443df061a.png">

![mobile-brand-view](https://user-images.githubusercontent.com/43003062/54428307-037e3980-4715-11e9-976f-04cbec386e82.png)

**Comment by Cleop** [comment]
This is a bug. Despite the fact that these images should be being styled in the same way as the venue images (with the same class):
![image](https://user-images.githubusercontent.com/16775804/54440220-2ec35180-4732-11e9-8f61-071d22833f2e.png)

I think that the css used in the class isn't functioning properly because the brand image is being viewed in a `<div>` element not an `<img>` tag and so the css is not displaying properly. I think the solution may be to make the brand `<div>` into an `<img>` which is what I will try now.

**Comment by Cleop** [comment]
Yes, by changing the tags the styling now works as it should locally:

<img src="https://user-images.githubusercontent.com/16775804/54441138-0a687480-4734-11e9-9f91-92bd60703421.png" width=300px />

![image](https://user-images.githubusercontent.com/16775804/54441163-16eccd00-4734-11e9-9bb9-9ee51ca3e0d8.png)
