### ISSUE TITLE
Brand pages not showing drinks

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#505]
We've found three brands that have associated drinks, but the drinks don't show up on the brands pages:

- Britvic
- Gunrz
- Diferente

All three seem to have two brand pages (database entries) associated with them so we're guessing that has something to do with it?

We're not sure what to do - by deleting one we could lose both (this kind of thing happened with a venue that was entered twice by the manager).

**Comment by iteles** [comment]
@jussi-club-soda Thanks for the detective work on this one! That sounds like a feasible explanation so we'll look into it. We'll also look to understand why this happened - it may have been with the bulk data uploads.

We'll do some tests on this in staging and update you with a solution for deleting one.

**Comment by Cleop** [comment]
At the moment we're providing the brand delete function with a brand got using its slug (so if the slug is the same, which it will be if they have the same name), you are right it will delete both of them. So hold off deleting them for now!

I should be able to change this so that the brand is got using the entry id and that way only one entry would be deleted at a time.

**Comment by Cleop** [comment]
I've also added a function so that you cannot create an already existing brand as a new brand to prevent this from happening in the future.
