### ISSUE TITLE
Category filters

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#506]
On the drinks listing page (https://www.clubsodaguide.com/search/drinks), using the drink type drop-down: clicking on a sub-category doesn't take out the parent category so nothing changes.

For example, first selecting "beer" and then "IPA" still shows all the "beer", not just IPAs. You need to untick the top category.

**Comment by iteles** [comment]
@jussi-club-soda Thanks for raising this issue. Is this something that has come up as a result of your user testing?

The filtering was built in this way to avoid confusion - we had a very similar situation for a different project which we carried over learnings from, but your audience may be different.

The question around causing confusion with the UI arises in the following two scenarios:
+ A user ticks `Beer` and then ticks `IPA` and the results change, with the pink box for the `Beer` filter disappearing altogether - in this scenario we found that users were sometimes confused because one of the filters they had specifically checked had disappeared
+ A user going into the styles first and ticking `IPA`, then going back in and deciding they want to tick `Beer` as a whole, but this wouldn't work because a sub-category was already ticked - the logic proposed here would mean that this scenario couldn't really be catered for effectively

**Proposed solution:**
If this _has_ been tested with users and has come from them, one solution could be that if a (or multiple) sub-category is ticked ("IPA" for example) as well as the overall category of "Beer", all Beer drinks are shows, _but those with the IPA sub-category are rearranged to be shown **first**_ followed by the rest of the drinks in the Beer category.

This is an enhancement on the #38 and follows on from the testing in https://github.com/club-soda/club-soda-guide/issues/43#issuecomment-457576202 :+1:

**Comment by jessyclubsoda** [comment]
@iteles Hi yeah this has come up as a result of user functionality. 

I think for us the best solution would be that whenever a drink grouping is clicked on whether it is a style or a type, it drops out whatever had been previously selected. We think that just having the specific type at the top of a longer list would be confusing. Generally we think that our users would only be looking for one specific style of drink so wouldn't be concerned with the previous one dropping out necessarily.

Is this feasible?

**Comment by iteles** [comment]
@jessyclubsoda We'll get on it, thanks for the reply and insight 😊

**Comment by SimonLab** [comment]
> I think for us the best solution would be that whenever a drink grouping is clicked on whether it is a style or a type, it drops out whatever had been previously selected

This is more complicated to implement as it requires to know when a filter has been selected (eg style selected after type).

I've created a PR which implement the logic describe on the first comment https://github.com/club-soda/club-soda-guide/issues/506#issue-425525598 . I would suggest to test this feature when the PR is merged and see if it resolve the issue as I would prefer to avoid adding complexity to the code

**Comment by jessyclubsoda** [comment]
Looks great! Thanks!
