### ISSUE TITLE
"Find one near me" doesn't work on brand pages

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#507]
From a brand page's "Places that Serve XXX" section, clicking on the "Find one near me" button just takes you back to the complete list of venues, rather than anything location based.

**Comment by Cleop** [comment]
- [x] Take a user to the venues search page displaying venues based on their location
- [ ] Ensure those venues all serve the brand that they came from

**Comment by Cleop** [comment]
@jussi-club-soda - you're right this button had not been edited from what we originally hard coded it to.

In terms of the options for what this should now do...

The preferable technical implementation is that clicking that button would reload the brand page that the user is on with the 'places that serve' section ordered with the closest venues appearing first (previously those venues were ordered by CS Score). We could change the wording of the button to make sure this is clear e.g. 'Order by '... Nearest to me/ Proximity/Location.

The other option is to redirect to the venue search page and order the venues by location only showing venues serving that brand. This is more difficult from a technical perspective because of the database relationships between venues and brands and the fact that until now the search page has not had to forge that relationship at all. Whereas on the brand page the relationship already exists.

Please let me know which implementation you'd like us to build.

**Comment by jessyclubsoda** [comment]
@Cleop The preferable implementation of just reloading the brand page with the closest venues sounds good to us!

**Comment by Cleop** [comment]
- [ ] Need to sort out view functions so that it doesn't override location ordering with ordering by CS Score
- [ ] Need to change show script url from hardcoded heineken to brand name
