### ISSUE TITLE
Venue editing bug

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#510]
Bug reports from the team:

ANJA: Strange bug. We are fixing venue content. 

I was editing the bio on Coach & Horses UB10 8LJ

I went into the venue, changed a couple of words, then clicked save.

the page refreshes, all information has been deleted apart from the bio, so name, address etc. I tried again and the same issue. So I've no choice but to leave the content of the bio as is, because any edit makes it impossible to save the venue.

JESSY: This just happened to me for The Telegraph EC2R 7AR (which is interestingly a duplicated venue although given that the Coach and Horses isn't I'm not sure if that's relevant)

**Comment by Cleop** [comment]
@jussi-club-soda from what I can see, this is because those venues have a couple of invalid fields:

![image](https://user-images.githubusercontent.com/16775804/55146261-1ee93b80-513c-11e9-8736-095c03836583.png)

That's because social media accounts must be a full web address not just a handle. These venues must have come from an import after we ran a script to fix this across all venues. So to resolve the issue you just need to change those fields e.g. https://twitter.com/telegraphec2 not telegraphec2

As you are trying to update the venue, the form is running the checks and has found the fields aren't in the correct format. Once you've corrected them you can make any usual edits.
