### ISSUE TITLE
Contact form for our Contact Us page

### ISSUE THREAD

**Issue by jessyclubsoda** [club-soda/club-soda-guide#594]
As a *user*, I would like to be able to clearly and easily contact the website

Here is a [simple wireframe](https://wireframe.cc/UmhoCz) of how this form could look

**Requirements** for this issue

- [x] Form for Name, Email, Message

- [x] Client side validation

Name field - no validation required
Email field - making sure there is an @ and something at the end
Message field - making sure it is not blank
Removal of any html or script tags which could be malicious

Using an 'error fields only' approach so that when the page reloads, any fields that have been correctly filled out will remain filled out. 

- [x] Server side validation

- [x] When filled in, form sends contents to email *guide@joinclubsoda.co.uk*

- [x] Confirmation of submission notice

- [x] GDPR agreement

**This Contact Us page will be separate from other static pages for reasons of security**

**Comment by iteles** [comment]
@jessyclubsoda 

A couple of questions on this:
+ Could we expand on the client side validation a little more please? We'll need to anyway before this issue can be worked on in future. Potential validations would be:
  + Checking no field is blank (is email mandatory? Would people _want_ to contact you anonymously? Would you want them to be able to do that? You'd need to weight this against the odds people will forget to fill in the field and then be expecting a reply you have no way of providing!) 
  + Checking the field name is longer than 2 characters
  + Basic validation for the email field format (making sure there an '@' and a '.something' at the end for example)
  + Stripping any html or script tags that could be malicious
+ What do you mean by hyperlinked social media bubbles? Are you thinking a twitter icon, etc that would lead you directly to Club Soda's pages on this? Where would these  appear? Would they be elsewhere on the page or directly linked to the contact form?

A note on considerations:
+ This doesn't have to be a PHP form as PHP is a specific programming language (in this case, because we didn't build the rest of the website in PHP, it would be ideal if it _wasn't_ so as not to mix languages), we can just call this issue 'Contact form on Contact Us page' for example to avoid confusion 😊 
+ Spam may also be a consideration here, but I would propose you set up the form and then have a separate issue to enhance the form in this way
+ At this stage, it would probably be wise to take GDPR into account given a name and email are personally identifiable pieces of data
  + An example of a checkbox we could add to the form would be something like the below and we'd then need to consider what you'd do if the visitor chose not to give consent:
![image](https://user-images.githubusercontent.com/4185328/58897287-df1c7280-86ef-11e9-817d-c3fd511f234e.png)

**Comment by jessyclubsoda** [comment]
@iteles 

**Client side validation**
I think we would want a couple of forms of client side validation. 

- Name field: no validation required

- Email field: making sure there is an @ and a something at the end - I am not concerned about people being able to contact us anonymously, I would prefer just to reduce spam

- Message field: making sure it is not blank

It would also be good to remove any malicious html or script tags definitely.

We’ll also want the page to have an ‘error fields only’ approach so that if, for example, someone has already written their message but enters their email in the wrong format, the message will not be wiped. 

Will we need to include some server side validation as well? 

We’ll also want some kind of submission confirmation notice.

**Social media bubbles**
Yes this is separate from the contact form - perhaps I should open it as a separate issue?, and just a case of wanting some more eye-catching design as part of the contact us page.
I like the use of circular buttons like so:
![Circular social buttons](https://user-images.githubusercontent.com/49029914/58961736-a9d05d00-87a1-11e9-9f48-7185f7127be3.PNG)

I think it’d be ideal to use the left hand side of the page to link to our socials and Club Soda websites. 

**PHP**
Yes just realised this! Still struggling to get my head round all the different languages/frameworks etc. I'll update accordingly

**Spam**
I agree - based off of our venue listings form on the current website, we've only had one spam submission get through over the past three months. I don't know if contact forms are more easily attacked but based off of that, it's something to bear in mind but not urgent

**GPDR**
Looks good!

**Comment by iteles** [comment]
@jessyclubsoda This is all great stuff.
Could you please update the top comment with all of these clarifications and additional requirements?

And yes, I think it would be good to open a separate issue on adding social media bubbles to the contact us page :+1:

**Comment by SimonLab** [comment]
Current contact us page:
![image](https://user-images.githubusercontent.com/6057298/67583783-290c0080-f744-11e9-86de-e0ea43d70867.png)

**Comment by SimonLab** [comment]
with the background image:
![image](https://user-images.githubusercontent.com/6057298/67619558-ff5ee200-f7f4-11e9-9ede-0580014029d7.png)

**Comment by jessyclubsoda** [comment]
@SimonLab Looking great! One question on this - is it possible to set up the social media buttons so that they open in a new tab rather than redirecting away from the website?
