### ISSUE TITLE
Member drinks listed at the top of the drinks page 

### ISSUE THREAD

**Issue by jessyclubsoda** [club-soda/club-soda-guide#599]
> As a *member brand*, I would like to see my drinks prioritised above non-member drinks

Currently when you click on the [Drinks](http://www.clubsodaguide.com/drinks) page, the same drinks come up in the same order

![Drinks page](https://user-images.githubusercontent.com/49029914/58635212-36cc6f80-82e5-11e9-8e0c-0cc29be5869c.PNG)

We would like to be able to prioritise member drinks over non-member drinks so that they show up higher, similar to the way that we can do with the carousel on the front page

**Requirements** for this issue

- [x] Ranking of drinks can apply to the drinks page as well as the carousel

**Comment by iteles** [comment]
@jessyclubsoda At the moment, the carousel on the homepage is based on weighting, added by CS admins https://github.com/club-soda/club-soda-guide/issues/8 - do we want to do away with that granular control in favour of bubbling member brand drinks to the top?

How do you wan the drinks ordered? As long as it's a member brand drink, it goes to the top? Do we need to consider what happens when one brand has a lot of drinks and pushes your other member brands further down the page?

The carousel specifically is limited to a certain number of drinks. How do we deal with this for member brands that have a lot of drinks? Pick one drink from each brand?

**Comment by jessyclubsoda** [comment]
@iteles Is it possible to have that weighting that forms the carousel on the homepage also apply to the main drinks page? 

That way we could weight certain drinks from member brands without having to put all of the drinks from one brand up - the same way we do on the carousel.

**Comment by iteles** [comment]
Definitely, that would also be the simplest way to do it!

**Comment by SimonLab** [comment]
The logic to sort the drinks by weight was almost there:
https://github.com/club-soda/club-soda-guide/blob/24fd810f3322399ba3e406694bec423acf8f6fde/lib/cs_guide_web/controllers/search_drink_controller.ex#L10

Because the weighting can be `nil` the sorting returned all the drinks with `nil` first. The following code will replace all the nil value by 0 and the order should be correct after that
```
|> Enum.sort_by(&(&1.weighting || 0), &>=/2)
```
