### ISSUE TITLE
Reordering of drinks on venue pages

### ISSUE THREAD

**Issue by jessyclubsoda** [club-soda/club-soda-guide#600]
> As a *user*, I would like to be able to see the less common/available drinks first when I visit a venue page

Currently when you click on a venue page, the way that the drinks which are listed there are displayed is through grouping by categories in a certain order

![Drinks on venue pages](https://user-images.githubusercontent.com/49029914/58635382-a80c2280-82e5-11e9-8f8c-d3d716d91af8.PNG)

As a *user*, this order isn't particularly useful to me in terms of how the information is displayed. If I am looking up a venue, I would like to see the more *obscure* or *less obviously available* drinks first. I would also like to see *similar* drinks grouped next to each other. 

By this I mean that beer, cider, wines, spirits appear first with softs and tonics/mixers appearing later next to each other

**Requirements** for this issue

- [x] Reorder the way that the drinks displayed on the venue pages to go: beers, ciders, wines, spirits, softs, tonics/mixers

**Comment by SimonLab** [comment]
A drink can have multiple types (not sure if this occurs often but it can happen) so the first step is to find the most common type for each venue's drink.
Once we have the main type for the drinks we need to find a way to sort the drinks depending on their type, ie beers > ciders > wines > spirits > softs > tonics/mixers > other-types. Now Looking at the best way to do this.

**Comment by iteles** [comment]
@jessyclubsoda On this issue, it's worth noting that as agreed when it was first put together, the ordering here is dependent on the category names staying the same - they are currently hard-coded in. If these names are changed (which is possible in the admin section), the ordering will not work as expected.

Would you like to open an issue (maybe with a low priority) to capture a future development that evolves this functionality and also gives you control of the ordering from the admin section? I don't know if there's a use case for this so I didn't want to open an issue on it myself!

@SimonLab Briefly re-opening this issue so that we can add a note to the docs please 🙏
