### ISSUE TITLE
Line breaks in description boxes

### ISSUE THREAD

**Issue by jessyclubsoda** [club-soda/club-soda-guide#628]
We are having some problems inserting line breaks into text boxes.

It says in the guide that we should be able to use break tags to do so for venue descriptions (and I assumed other text boxes across the site). 

However, these don't seem to be working on the staging or live site.

Normally this isn't a problem because venue description boxes accept the enter key but brand description boxes do not, and they won't accept break tags either.

Some images below:
![Kolibri with enter in text box](https://user-images.githubusercontent.com/49029914/65775995-20221200-e139-11e9-89e1-980006e0d8c5.png)
Here I just tried to use the enter key in the text box in the way that we can with venue descriptions
But no breaks came up 
![Kolibri with no breaks](https://user-images.githubusercontent.com/49029914/65775998-20221200-e139-11e9-891d-7afda114e0f8.png)

Here I tried to use break tags

![Kolibri with break tags](https://user-images.githubusercontent.com/49029914/65775994-1f897b80-e139-11e9-908d-362662160038.png)

But no breaks came up
![Kolibri with no breaks after tagging](https://user-images.githubusercontent.com/49029914/65775997-20221200-e139-11e9-8921-22d8df218ef7.png)

I'm not sure if this is either because 1. I'm using break tags wrong or 2. The text boxes aren't accepting them
Ideally it would be best if the brand description boxes just accepted the enter key in the way they do for venues but otherwise it'd be great if they could have some paragraphing possible

Either way it doesn't currently seem to be working as the guide suggests it would

**Comment by SimonLab** [comment]
A few paths in mind to investigate:
- Are the line break properly saved in Postgres (are they removed on saved?)
- Is the drink description retrieved from Postgres the correct one and not an older one which don't have line breaks
- Are line breaks properly interpreted/displayed on the page? Do we need to call the `raw` function for example?
![image](https://user-images.githubusercontent.com/6057298/66036898-4b747a80-e506-11e9-8b6b-84717c3163fd.png)

see https://hexdocs.pm/phoenix_html/Phoenix.HTML.html

**Comment by SimonLab** [comment]
- The inputs for drinks, venues and brands are all created with textareas
- When the description is saved, all html tags are removed (ie <br>, <h1>,...) and new lines in the description are saved as `\n` in Postgres
- All descriptions are displayed in a `p` tag but only the venue description converts `\r` to `<br>`

Now looking at how venues do this conversion (maybe with [text_to_html function](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Format.html#text_to_html/2) ?) and how to apply the same logic to brands and drinks

**Comment by jessyclubsoda** [comment]
Thanks for taking a look at this @SimonLab 

Looking on staging it seems that we can still only do one line break e.g. we can't create paragraphs
![Amaizedrinks with enter](https://user-images.githubusercontent.com/49029914/66199382-62e26d80-e696-11e9-83a9-595c1ed237af.png)
Here even though I've used the enter button twice it only gives me one break
![Amaizedrinks no dice with enter](https://user-images.githubusercontent.com/49029914/66199456-8c9b9480-e696-11e9-8ddb-332d99adc91a.png)

Similarly  < br > tags seem to have no effect

**Comment by SimonLab** [comment]
Thanks for spotting that @jessyclubsoda .
This is due to the `text_to_html` function(https://hexdocs.pm/phoenix_html/Phoenix.HTML.Format.html#text_to_html/2)
![image](https://user-images.githubusercontent.com/6057298/66218903-0dbc5100-e6c2-11e9-8652-5a5c80fef339.png)

So new paragraphs (<p></p> tags) are created if there are 2 or more consecutive lines.
This means that empty paragraph are removed. If you add a space in front of the new line then a new paragraph will be created to only display the space.

I think that's why the `add_line_breaks` helper function is used for the venues' description and not the `text_to_html` function:
https://github.com/club-soda/club-soda-guide/blob/75a3446dd2814bf15a7210a2533a0146311f99aa/lib/cs_guide_web/views/venue_view.ex#L58-L60
I'll do a bit more test but I think the solution is to reuse the `add_line_breaks` function
