### ISSUE TITLE
Promoted drinks on homepage

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#8]
As a customer visiting the Club Soda Guide homepage,
I would like to see a list of featured drinks, 
so I can discover new alcohol free / low alcohol products

## Acceptance Criteria
+ [x] Displays as a carousel
  + [x] Swipe action on mobile
+ [x] Currently capped at 15 drinks
+ [x] Drinks with the highest rating (3, as per #74) are displayed first, with lower weighted drinks displayed last (towards the right)
~+ [ ] Drinks displayed are randomised (each user should see a different set of drinks) - this may require us to  fix the number of drinks in each weighting category displayed in the carousel, TBC~ Moved to #121 as lower priority as agreed (weightings can be manually worked around without relying on randomisation for now)

**Comment by iteles** [comment]
Affected by weighting in #74

**Comment by Cleop** [comment]
For the drinks cards, I've added the brand to the title as we discussed this alongside the drink name/flavour:
![image](https://user-images.githubusercontent.com/16775804/46492289-03444e80-c805-11e8-9c51-4605a29c89b4.png)

However it now seems quite 'busy', @Danwhy previously suggested putting the brand name in underneath and smaller. I'm wondering whether to do that or even the opposite and putting the name/flavour underneath and smaller. I think we need to look at several examples to think about what makes sense for most drinks. E.g. Big Drop (Pale Ale), Seedlip (Spice 94), Real Kombucha (Royal Flush) rather than the other way around.

**Comment by iteles** [comment]
Carried out in https://github.com/club-soda/club-soda-guide/pull/118

**Comment by jussi-club-soda** [comment]
I can't see this one working yet? @iteles ?

**Comment by iteles** [comment]
@jussi-club-soda Agreed, I think the weighting is just back to front because it accounted for the field having a value but not for it having no value at all (as per our imported data).

@Cleop  I just tested this as follows:

Homepage starts off looking like this:
![image](https://user-images.githubusercontent.com/4185328/49604870-f5d34e00-f986-11e8-80d1-f973d0a07154.png)

I can see that there is no weighting for Double Dutch Indian Tonic Water, which is the first drink in the carousel:
![image](https://user-images.githubusercontent.com/4185328/49604948-25825600-f987-11e8-875d-8ef38802a4b0.png)

I add a weighting of '2' to the DRGN Turmeric Superdrink:
**Could we please also have a line in the documentation about weighting in drinks and its effect as well as maybe a guide next to the field label itself on what values it will accept?**
![image](https://user-images.githubusercontent.com/4185328/49605181-c113c680-f987-11e8-9428-0680a593c5fd.png)

It disappears altogether from the carousel:

![image](https://user-images.githubusercontent.com/4185328/49605194-cb35c500-f987-11e8-9b7a-76245a1b846d.png)

**Comment by Cleop** [comment]
I opted for an 'case' statement for the nil values as I didn't want the possibility of an empty carousel. So I replaced instances of 'nil' with 0 so these drinks weren't above the weighted drinks.

I then resolved the looping carousel bug which was occurring because the index was being set to the last item in the array but it wouldn't then display the next items from the beginning. So you would see the last card on its own. To do this we needed to connect the two ends together. `modBy` proved perfect for this as it enables you to count up to a maximum number (the max array index) whilst also accounting for the next items in the range e.g. going back to 1,2,3.
