### ISSUE TITLE
Venue should confirm their email before venue listing is published

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#90]
As a venue,
I should receive an email asking me to confirm my email address before my listing is published,
so I have a valid email I can receive notifications to.

**Comment by iteles** [comment]
@jussi-club-soda At the moment, we're publishing the listings as they are created, so I believe this is no longer relevant?

In our sprint 1 planning session we discussed having the venues listed straight away as you can then edit or delete them as an admin. We had discussed the lower priority 'reviewed' feature as part of this: #87

**Comment by jussi-club-soda** [comment]
@iteles Yes happy to close this, as long as the process otherwise has some basic protection in place (I'm thinking ReCaptcha or something similar to stop bots from creating listings).

**Comment by iteles** [comment]
@jussi-club-soda Please do open that additional issue on stopping bots from creating

**Comment by nelsonic** [comment]
@jussi-club-soda "_unpublishing_" a venue listing 
will be a "one-click" operation from the Admin>Venues dashboard/overview.
so avoiding/fighting "spam" will be reasonably easy (_to start with_). 

We _agree_ that requiring people to _verify_ their email address is a _good_ workflow step in _general_,
because email will be the _primary_ means of communicating with all "users" of the system/app
and without a _valid_ email address people will not be able to login or reset password ...
so after creating content they will be "locked out" ...

_However_ validating an email address in/by itself is not a _good_ means of "fighting spam",
spammers have _many_ "real" email addresses they can use to post bad content,
relying on email verification as a "signal" for quality content is likely to lead to "false positives". 

Google no longer uses Captchas because "spam bots" are regularly circumventing them.
see: https://github.com/dwyl/contact/issues/6#issuecomment-428232644 

Please don't "worry" about verifying users before allowing content to be posted/published.
**`if`** spam becomes a problem we can _quickly_/_easily_ remedy it.
