### ISSUE TITLE
What are the related content types?

### ISSUE THREAD

**Issue by iteles** [club-soda/club-soda-guide#95]
Moved these questions from @nelsonic to their own issue from https://github.com/club-soda/club-soda-guide/issues/5#issuecomment-422048098 so that we are able to discuss each topic separately:

## 3. _Secondary_ Content?

3. What are the _related_ (_secondary_) content types for each of the _primary_ content types.
For _example_: 
  + ***Product*** ratings/reviews?
  + ***Venue*** ratings/reviews?
  + ***Event*** rating/review? (_e.g: Mindful Drinking Festival_ https://mindfuldrinkingfestival.com/mindful-drinking )
  + ***User Images***? _note_: we do not need to _store_ the images, we could simply store a _reference_ to them e.g: link to the Twitter/Instagram post where the drink/venue/event was tagged/mentioned.

**Comment by jussi-club-soda** [comment]
Ratings & reviews - we have been debating whether to have them on the site or not... On our current version customers can both rate (1 to 5 stars on four aspects: overall, range of low/no alcohol drinks, visibility of low/no drinks, and customer service) and review (free form text) venues - our thinking was to both get interesting/useful information and to confirm that venues are as good as they say they are (based on their Club Soda Score self-assessment) - this hasn't been a very popular feature of the site. It is also open to easy abuse, I have caught at least two venue managers giving themselves 5 stars...

So this is something we will probably come back to at some stage, but in this build we will most likely ignore it. The one thing we thought we'd use is to give customers an option to flag a venue to Club Soda if they have any concerns (for example after visiting a "5 star venue" that has a really poor range of drinks) - they can just send us a quick message so we can investigate and take action if necessary (by for example contacting them, visiting them, editing the venue listing, or even deleting them). 

Not sure I know what user images would be? Customers uploading photos from venues? Or something else?

**Comment by nelsonic** [comment]
@jussi-club-soda abuse of rating/review systems is (_almost_) _inevitable_.
We can track the IP address, device "fingerprint" and require _registration_ (_or "login with Fb/Goog"_) to help _mitigate_ fake or "self" reviews, but nobody has figured out how to completely _eliminate_ them. 
https://www.npr.org/2018/07/30/629800775/some-amazon-reviews-are-too-good-to-be-believed-theyre-paid-for
CS need to be _clear_ that "pay for reviews" is unacceptable in the Terms & Conditions
and then include a way to "flag" a review as a feature in the _backlog_. [please open an issue for this]

### Our _reasoning_ for wanting to include (_Prioritise_) Ratings/Reviews "_ASAP_" are:

1. **User Interaction, Experience & Engagement**: the easiest "1-click" way of encouraging feedback/interaction from users is a rating which will:
  + ***Increase Engagement***: keeping users _engaged_ with your site/app for longer/deeper.
  + ***Promote*** "**ownership**": give users a sense of "ownership" for their favourite venue/product(s). People will come _back_ to the pages they have reviewed to see how they are "doing" _especially_ if other CS users can "_rate the review_" as "helpful" e.g:
![image](https://user-images.githubusercontent.com/194400/45913708-d02ab400-be2f-11e8-8c1e-fd5e9ff0dff7.png)
  + **Gamify** UX (_slightly_) as we can show people their review/rating count and place them on a "leaderboard" of reviewers. This feature should be discussed further, and does not _need_ to be implemented _at all_! However the basics of _collecting_ the rating/review data is the starting point.
  e.g: https://www.amazon.com/reviews/top-reviewers
2. **Relevance**: The Natural "Sorting Order" for products and venues in a "crowded market" is "by customer rating".
If we collect the ratings/reviews as soon as possible, we can _already_ start displaying _relevance_ in the lists of products/venues we present to people searching ... 

> Armed with a bank of _geo-located_ review/rating data we could even get _fancy_ 
and _automate_ content creation: "_Top 10 Venues in `{City Name}`_" or "_Most popular alcohol-free cocktails in `{City Name}` for `{YEAR}`_" which are good ["listicles"](https://en.wikipedia.org/wiki/Listicle) that are both highly "shareable" and can get **_fantastic_ SEO** because we can _mimic_ the **_exact_ search query** users are typing (_or asking Siri/Alexa!_) 😮 

3. ***Community***: having reviews (_and a "reply" feature_) will foster an _organic_ community on the site where:
  + **Users** can _add_ to existing reviews with additional feedback/commentary 
e.g: "thanks for the insider tip that `{Venue Name}` has a board games night, we loved it!"
  + **Venue owners/managers** can ***respond*** to _negative_ reviews such as "long wait time" or "poor customer service" or "woeful range of non-alcoholic beverages" etc.
As a prospective customer, seeing a _response_ from the Product/Venue owner is _great_ reassurance that they are "_listening_" and _addressing_ concerns. And if a Venue owner "takes on" any "constructive feedback" and _improves_ their venue/process as a result, they can "_convert_" an "unhappy customer" into an "_evangelist_" or "_brand ambassador_". 
see: https://neilpatel.com/blog/unhappy-customers-into-resource

4. **Data _Goldmine_**: Brand Mangers will pay _handsomely_ for the (_anonymised and aggregated_) ***Demographic Data*** ("_insights_") for the people who posted the ratings/reviews for both their _own_ and their _competitors_ products. If we can _capture_ this data and allow Brands to "_subscribe_" to it, we can _easily_ justify the "dev cost" of building this feature. I _hypothesize_ that it has a **10x - 100x ROI**! 💰 📈 

5. ***SEO***! #83  🔍 (_probably most important for the long-term success of the project...!_)
by capturing ratings/reviews _now_ and rendering them with the correct semantics and aria-labels
we can _dramatically_ increase the SEO Raking of _all_ pages on Club Soda such that the CS page will appear at (_or near_) the Top of the SERPs for "_organic_" product and venue searches!
![image](https://user-images.githubusercontent.com/194400/45913364-d9645280-be28-11e8-9413-fb855e065038.png)
Notice how the venues with ratings _always_ appear at the Top of the Google Search. 
If we can get CS users to login to CS using their Google Account (_not currently on the feature "roadmap" but it could be!_) we can "cross-post" venue reviews to both CS and Google which will give Venue owners a **_massive_ incentive** to use the CS site and **_actively_ manage** their ["_sosh_"](https://www.urbandictionary.com/define.php?term=Sosh) 😉 
For now, simply collecting the ratings and rendering them correctly will be "enough" to derive _many_ SEO benefits. This _alone_ should be our short-term "_justification_" for prioritising Rating/Reviews for **Sprint 2**. ⬆️

6. **Simplicity**: the interface for data capture is simple to create (_we can build it in a couple of days_) which means we can _test_ the feature quickly and iterate on user feedback. ♻️ 

## _Next Actions_

@iteles this issue is _good_ to discuss related/secondary content types in _general_. 👍 
_HoweveR_ I _suggest_ that we open a **_specific_ Ratings/Reviews** issue (_user story_) which should be framed from the perspective of the "Conscious Drinker" User _first_, followed by Venue and Brand/Product managers.

@Danwhy in the **Ratings/Reviews** issue we will need to discuss how to _relate_ content types.
There is a good way to _generalise_ this so that we can apply a rating/review to _anything_. 🤓 

@jussi-club-soda _for now_, **_ignore_ user images**. User images should be _separate_ [`priority-3`] issue.
